# Generated by Django 3.2.8 on 2021-10-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('character_class', models.CharField(max_length=50)),
                ('HP', models.IntegerField()),
                ('damage_die', models.CharField(max_length=10)),
                ('coin', models.IntegerField()),
                ('STR', models.IntegerField()),
                ('DEX', models.IntegerField()),
                ('CON', models.IntegerField()),
                ('INT', models.IntegerField()),
                ('WIS', models.IntegerField()),
                ('CHA', models.IntegerField()),
                ('equipment', models.TextField()),
                ('spells', models.TextField()),
            ],
        ),
    ]
